### ISSUE TITLE
这么好的模板，不要弃坑啊~

### ISSUE THREAD

**Issue by Hellowor1d** [liyanlong/nuxt-egg#10]
看了作者和天猪在egg 的 issue 下的讨论，追过来的，下载试了一把报错
```
[nuxt] Building error TypeError: Nuxt is not a constructor
    at NuxtEggApplication.get nuxt [as nuxt] (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/nuxt-egg/app/extend/application.js:8:20)
    at /Users/liuml/Workspace/personal/nuxt-egg/node_modules/nuxt-egg/app.js:7:17
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:65:19)
    at /Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:50:10)
    at toPromise (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:118:63)
    at next (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:69:7)
    at /Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:50:10)
    at toPromise (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:118:63)
    at next (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/liuml/Workspace/personal/nuxt-egg/node_modules/co/index.js:69:7)
```

**Comment by liyanlong** [comment]
感谢 关注， 最近一直在弄业务代码。 这块确实荒废了,  抽空我去更新下~

**Comment by hurely** [comment]
期待更新下 报错了

**Comment by dipu-bd** [comment]
I am facing the same problem. Can you explain in english please?

**Comment by superlbr** [comment]
http://nuxt-egg.liylblog.com is not in use
